#!/bin/sh

mv /etc/banner /etc/banner_tmp

# add SuperHouse ascii art
SUPERHOUSE="   _____ __  ______  __________  __  ______  __  _______ ______
   / ___// / / / __ \/ ____/ __ \/ / / / __ \/ / / / ___// ____/
  \__ \/ / / / /_/ / __/ / /_/ / /_/ / / / / / / /\__ \/ __/
 ___/ / /_/ / ____/ /___/ _, _/ __  / /_/ / /_/ /___/ / /___
/____/\____/_/   /_____/_/ |_/_/ /_/\____/\____//____/_____/"

echo "$SUPERHOUSE" > /etc/banner

# add Omega firmware version
version=$(uci get onion.@onion[0].version)
build=$(uci get onion.@onion[0].build)
echo " -----------------------------------------------------" >> /etc/banner
echo "   Ω-ware: $version b$build" >> /etc/banner
echo " -----------------------------------------------------" >> /etc/banner

# old code to preserve bottom of old banner
#sed -e 9,14d -e 1,5d /etc/banner_tmp | cat >> /etc/banner

rm /etc/banner_tmp
